### ISSUE TITLE
Diamond database version

### ISSUE THREAD

**Issue by jwestrob** [geronimp/enrichM#40]
Hi! I just started using enrichM and everything's going well, but I'm primarily interested in the KO annotations. However, when I go to annotate using the uniref diamond database, I get an error stating:

`Error: Database was built with a different version of Diamond and is incompatible.`

I'm downloading the uniref100 database on my own and I'll make a new diamond database out of it, but I'm not sure if that will mess anything up, so I thought I'd ask- which version of Diamond was used to construct uniref100.dmnd? I can just install that version into a conda virtual environment and use that to annotate with KO if need be.

Thank you so much!!

**Comment by geronimp** [comment]
Hi Jacob, thanks for flagging this. Can I ask what version enrichm database you are using? the latest version (v2) was created with DIAMOND v0.9.6. Recreating the diamond database will require some manipulation of the sequences because to make things more efficient I formatted the sequences to contain KEGG orthologous (KO) IDs in the headers (in the format seqname~KO_ID). I also only use the KO annotated portion of UniRef, so you will have to subset by that portion as well. If you do that, you shouldnt have any problems.

It seems every time diamond updates any previous database becomes incompatible which causes some annoying-ness while DIAMOND is making regular releases. Over the next week im looking at wrapping enrichm up in some docker or guix environments which will provide a more sustainable solution to this problem.

Thanks,

Joel

**Comment by jwestrob** [comment]
Oh, alright! I was using Diamond v0.9.22. That's the newest version on the Anaconda cloud, so this might pop up again for other people.

Do you happen to know where to get v0.9.6? I checked the github repo (https://github.com/bbuchfink/diamond/blob/master/src/ChangeLog) and found only up to 0.9.22.

Thanks again for the help.

**Comment by jwestrob** [comment]
Oh, and I forgot to answer your question - I'm using enrichm v0.2.0.

**Comment by geronimp** [comment]
DIAMOND v0.9.6 is in the change log but its pretty far back. I'll update the DIAMOND database and make a new release of the enrichm database

**Comment by jwestrob** [comment]
I don't know why I couldn't find that in the changelog. Sorry about that! I feel kind of silly. Thanks for updating the database!

**Comment by geronimp** [comment]
Hey no worries I was confused for a sec too. Can you update the database by running:
`enrichm data` (you may need sudo privileges
this will download the new database (enrichm db v3), which will include the updated uniref db compatable with diamond v0.9.22. After which the issue should be resolved, but please let me know if anything else pops up!

**Comment by geronimp** [comment]
Hi Jacob, did you have any success with the new database version?

**Comment by jwestrob** [comment]
Yes I did! Sorry I forgot to tell you- I ran it late last night and everything worked great. Thanks again.
