### ISSUE TITLE
Directionality on reactions for enrichm pathway/explore?

### ISSUE THREAD

**Issue by TYMichaelsen** [geronimp/enrichM#74]
Hi Joel,

Since you're doing a major upgrade - could you make the network being generated from the `enrichm pathway` and `explore` functions directional? This information would be very helpful for generating meaningful de-novo metabolic networks and is available in the KEGG database. 

Best,
Thomas

**Comment by geronimp** [comment]
Hi Thomas, 

I'd love to include directionality but its not easy to do currently. The KEGG database provides directionality in its pathway maps, but the information is not easily accessed. You can find directionality if you parse pathway kgml files directly. However I suspect not providing the information openly is intentional, because the directionality of a reaction can depend on a lot of things and is rarely a "right" or "left" situation. The other choice would be to use KEGG's rpair database but to my knowledge support for that has been discontinued and they are no longer releasing updates. For now I'll add this as an enhancement and I'll look into it, but its unlikely to be in the next release as my thesis is looming and this is not a straight forward addition.

Thanks for the great suggestion though, I agree that it would be helpful

Thanks,
Joel

**Comment by TYMichaelsen** [comment]
Hi Joel,

Thanks for the response. I see and you are right - the computationally generated reaction maps are far from (likely) what happens in the real world!

Good luck with your thesis and looking forward to a new release of enrichm!

Best,
Thomas
